### ISSUE TITLE
Data storage 

### ISSUE THREAD

**Issue by dany-eduard** [nestorcortina/CRUD-con-NodeJS-y-MongoDB#1]
Hola de nuevo mi hermano.
Estoy interesado en seguir aprendiendo las tecnologías de la web y tengo algunas preguntas sobre tu proyecto

1) ¿Tienes una base de datos para almacenar los contactos? [Auto respuesta xD] Usas  MongoDB, omite esta cuestión.
2) Si es así ¿cómo funciona?
3) Tienes acceso a la información desde esa base de datos

**Comment by nexckycort** [comment]
MongoDB es un sistema de base de datos orientado a documentos, de esquema libre, esto significa que cada entrada o registro puede tener un esquema de datos diferente, con atributos o “columnas” que no tienen por qué repetirse de un registro a otro. Para lograr conectarnos de manera rápida y sencilla a la base de datos hacemos uso de un ODM llamado mongoose, que en palabras menos técnicas es una librería que nos permite realizar un esquema previo de como queremos almacenar los datos, consultas, inserciones y mucho más usando el lenguaje js.
Puedes ir a la página MongoDB Atlas y crear un cluster de manera gratuita, editar la cadena de conexión por la que te dan y probarlo.
Espero que haya resuelto tus dudas.
